steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    git init
    git submodule init
    git submodule update

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: '/bin/sh'
  args:
  - '-c'
  - |
     curl -sL https://github.com/gohugoio/hugo/releases/download/v0.69.2/hugo_0.69.2_Linux-64bit.tar.gz | tar -zxv
     ./hugo
     ./hugo deploy -v
     gcloud compute url-maps invalidate-cdn-cache jamesward-test --path "/*"
