steps:
- name: 'gcr.io/jamesward/firebase'
  entrypoint: '/bin/sh'
  args:
  - '-c'
  - |
     rm -rf themes
     git init
     git submodule add https://github.com/budparr/gohugo-theme-ananke.git themes/ananke
     
     curl -sL https://github.com/gohugoio/hugo/releases/download/v0.69.2/hugo_0.69.2_Linux-64bit.tar.gz | tar -zxv
     ./hugo

     firebase deploy --project=jamesward --only=hosting
