baseURL = "https://test.jamesward.com/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "ananke"

[deployment]
order = [".jpg$", ".gif$"]

[[deployment.targets]]
name = "gcs"
URL = "gs://jamesward-test"

[[deployment.matchers]]
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
